services:
    # Generator

    majora.oauth.random_generator:
        class: Majora\Component\OAuth\Generator\RandomTokenGenerator
        public: false
        arguments:
            - ''

    # Server

    majora.oauth.server:
        class: Majora\Component\OAuth\Server\Server
        arguments:
            - '@event_dispatcher'
            - ''
            - ''
            - ''
            - ''
            - ''
            - '@majora.oauth.random_generator'
            - password: '@majora.oauth.grant_extension.password'
              refresh_token: '@majora.oauth.grant_extension.refresh_token'

    oauth.server: '@majora.oauth.server'

    # Grant extension

    majora.oauth.grant_extension.password:
        class: Majora\Component\OAuth\GrantType\PasswordGrantExtension
        public: false
        arguments:
            - ''
            - '@security.password_encoder'

    majora.oauth.grant_extension.refresh_token:
        class: Majora\Component\OAuth\GrantType\RefreshTokenGrantExtension
        public: false
        arguments:
            - ''
            - ''

    # Loader

    majora.oauth.loader.orm.application:
        class: Majora\Component\OAuth\Loader\ORM\ApplicationLoader
        public: false
        tags:
            - { name: majora.loader, repository: "majora.oauth.repository.orm.application", entityClass: Majora\Component\OAuth\Entity\Application, entityCollection: Majora\Component\OAuth\Collection\ApplicationCollection }
            - { name: majora.alias, alias: "majora.oauth.loader.application" }

    majora.oauth.loader.orm.account:
        class: Majora\Component\OAuth\Loader\ORM\AccountLoader
        public: false
        tags:
            - { name: majora.loader, repository: "majora.oauth.repository.orm.account", entityClass: Majora\Component\OAuth\Entity\Account, entityCollection: Majora\Component\OAuth\Collection\AccountCollection }
            - { name: majora.alias, alias: "majora.oauth.loader.account" }

    majora.oauth.loader.orm.access_token:
        class: Majora\Component\OAuth\Loader\ORM\AccessTokenLoader
        public: false
        tags:
            - { name: majora.loader, repository: "majora.oauth.repository.orm.access_token", entityClass: Majora\Component\OAuth\Entity\AccessToken, entityCollection: Majora\Component\OAuth\Collection\AccessTokenCollection }
            - { name: majora.alias, alias: "majora.oauth.loader.access_token" }

    majora.oauth.loader.orm.refresh_token:
        class: Majora\Component\OAuth\Loader\ORM\RefreshTokenLoader
        public: false
        tags:
            - { name: majora.loader, repository: "majora.oauth.repository.orm.refresh_token", entityClass: Majora\Component\OAuth\Entity\RefreshToken, entityCollection: Majora\Component\OAuth\Collection\RefreshsTokenCollection }
            - { name: majora.alias, alias: "majora.oauth.loader.refresh_token" }

    # Repository

    majora.oauth.repository.orm.application:
        class: Majora\Component\OAuth\Repository\ORM\ApplicationRepository
        parent: majora.doctrine_repository.abstract
        public: false
        factory: ["@doctrine", getRepository]
        arguments:
            - Majora\Component\OAuth\Entity\Application
            - default
        tags:
            - { name: majora.alias, alias: oauth.repository.application }

    majora.oauth.repository.orm.account:
        class: Majora\Component\OAuth\Repository\ORM\AccountRepository
        parent: majora.doctrine_repository.abstract
        public: false
        factory: ["@doctrine", getRepository]
        arguments:
            - Majora\Component\OAuth\Entity\Account
            - default
        tags:
            - { name: majora.alias, alias: oauth.repository.account }

    majora.oauth.repository.orm.access_token:
        class: Majora\Component\OAuth\Repository\ORM\AccessTokenRepository
        parent: majora.doctrine_repository.abstract
        public: false
        factory: ["@doctrine", getRepository]
        arguments:
            - Majora\Component\OAuth\Entity\AccessToken
            - default
        tags:
            - { name: majora.alias, alias: oauth.repository.access_token }

    majora.oauth.repository.orm.refresh_token:
        class: Majora\Component\OAuth\Repository\ORM\RefreshTokenRepository
        parent: majora.doctrine_repository.abstract
        public: false
        factory: ["@doctrine", getRepository]
        arguments:
            - Majora\Component\OAuth\Entity\RefreshToken
            - default
        tags:
            - { name: majora.alias, alias: oauth.repository.refresh_token }