Majora\Component\OAuth\Entity\Token:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        access_token: AccessToken
        refresh_token: RefreshToken
    table: majora_oauth_token
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        hash:
            type: string
            length: 128
        expireIn:
            type: integer
    manyToOne:
        account:
            targetEntity: Majora\Component\OAuth\Entity\Account
            joinColumn:
                name: account_id
                referencedColumnName: id
        application:
            targetEntity: Majora\Component\OAuth\Entity\Application
            joinColumn:
                name: application_id
                referencedColumnName: id
